### ISSUE TITLE
demander l'autorisation de publier les images de leur visages aux sujets

### ISSUE THREAD

**Issue by laurentperrinet** [anaisbrgs/StageL3#8]
ça peut poser un problème éthique pour certains de voir leur visage sur internet (meme si c'est bien caché)

par exemple 

https://github.com/anaisbrgs/StageL3/blob/58adfca64eb837d33ece744a7c0960426776fe13/2018-03-21%20data_base.ipynb

ou

https://github.com/anaisbrgs/StageL3/blob/f34ed92dca00fdcc22f7e8535cb18d9ff965a4f0/dataset/left/Ana%C3%AFs_17.png

**Comment by NicolasCambon** [comment]
Pour Anaïs, Justine et moi cela ne nous pose pas de problème de les voir affichées. Par contre est-il possible que les données ne soit pas réutilisées par d'autres personnes?

**Comment by laurentperrinet** [comment]
super, ça ne me pose pas de probleme non plus :-)

pour que ces données ne soient pas réutilisées, il faut y mettre une licence particuliere, à choisir dans:

https://creativecommons.org/share-your-work/

comme par exemple:
https://creativecommons.org/licenses/by-nc-nd/4.0/

qui dit explictement:

> 
>  NoDerivatives — If you remix, transform, or build upon the material, you may not distribute the modified material.

**Comment by laurentperrinet** [comment]
à rajouter dans un fichier LICENCE à la racine + dans le dossier dataset

**Comment by laurentperrinet** [comment]
resolved in https://github.com/anaisbrgs/StageL3/commit/368664b7da5384f2914c5e1f0d16862ff9c72ae8
